/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Paola
 */
public class frmCRUD extends javax.swing.JFrame {

    /**
     * Creates new form frmCRUD
     */
    public frmCRUD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnActualizar = new com.k33ptoo.components.KButton();
        btnAgregar = new com.k33ptoo.components.KButton();
        btnEliminar = new com.k33ptoo.components.KButton();
        btnLimpiar = new com.k33ptoo.components.KButton();
        jLabel1 = new javax.swing.JLabel();
        txtEstadoProblemaCRUD = new javax.swing.JTextField();
        txtProblemaCRUD = new javax.swing.JTextField();
        txtAnoCRUD = new javax.swing.JTextField();
        ModeloCRUD = new javax.swing.JTextField();
        txtApellidoCRUD = new javax.swing.JTextField();
        MarcaCRUD = new javax.swing.JTextField();
        txtNombreCRUD = new javax.swing.JTextField();
        txtTelefonoCRUD1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbCoso = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(75, 186, 238));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnActualizar.setText("Actualizar");
        btnActualizar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnActualizar.setkBackGroundColor(new java.awt.Color(0, 90, 163));
        btnActualizar.setkEndColor(new java.awt.Color(93, 204, 255));
        btnActualizar.setkHoverEndColor(new java.awt.Color(93, 204, 255));
        btnActualizar.setkHoverForeGround(new java.awt.Color(0, 90, 163));
        btnActualizar.setkHoverStartColor(new java.awt.Color(0, 90, 163));
        btnActualizar.setkSelectedColor(new java.awt.Color(93, 204, 255));
        btnActualizar.setkStartColor(new java.awt.Color(0, 90, 163));
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, 110, 30));

        btnAgregar.setText("Agregar");
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAgregar.setkBackGroundColor(new java.awt.Color(60, 168, 131));
        btnAgregar.setkEndColor(new java.awt.Color(96, 229, 162));
        btnAgregar.setkHoverEndColor(new java.awt.Color(96, 229, 162));
        btnAgregar.setkHoverForeGround(new java.awt.Color(60, 168, 131));
        btnAgregar.setkHoverStartColor(new java.awt.Color(60, 168, 131));
        btnAgregar.setkSelectedColor(new java.awt.Color(96, 229, 162));
        btnAgregar.setkStartColor(new java.awt.Color(60, 168, 131));
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 110, 30));

        btnEliminar.setText("Eliminar");
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnEliminar.setkBackGroundColor(new java.awt.Color(176, 7, 96));
        btnEliminar.setkEndColor(new java.awt.Color(229, 86, 96));
        btnEliminar.setkHoverEndColor(new java.awt.Color(229, 86, 96));
        btnEliminar.setkHoverForeGround(new java.awt.Color(176, 7, 96));
        btnEliminar.setkHoverStartColor(new java.awt.Color(176, 7, 96));
        btnEliminar.setkSelectedColor(new java.awt.Color(229, 86, 96));
        btnEliminar.setkStartColor(new java.awt.Color(168, 0, 54));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, 100, 30));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLimpiar.setkBackGroundColor(new java.awt.Color(19, 38, 161));
        btnLimpiar.setkEndColor(new java.awt.Color(60, 26, 174));
        btnLimpiar.setkHoverEndColor(new java.awt.Color(60, 26, 174));
        btnLimpiar.setkHoverForeGround(new java.awt.Color(0, 90, 163));
        btnLimpiar.setkHoverStartColor(new java.awt.Color(0, 90, 163));
        btnLimpiar.setkSelectedColor(new java.awt.Color(60, 26, 174));
        btnLimpiar.setkStartColor(new java.awt.Color(0, 90, 163));
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, 100, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reparaciones");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        txtEstadoProblemaCRUD.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estado del Problema", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel1.add(txtEstadoProblemaCRUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, 180, 110));

        txtProblemaCRUD.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Problema", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel1.add(txtProblemaCRUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, 180, 110));

        txtAnoCRUD.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Año", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel1.add(txtAnoCRUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 210, 180, 50));

        ModeloCRUD.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Marca", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel1.add(ModeloCRUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 190, 50));

        txtApellidoCRUD.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel1.add(txtApellidoCRUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 190, 50));

        MarcaCRUD.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Marca", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel1.add(MarcaCRUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 190, 50));

        txtNombreCRUD.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel1.add(txtNombreCRUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, 190, 50));

        txtTelefonoCRUD1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        jPanel1.add(txtTelefonoCRUD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 190, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Rectangle 118.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 230, 350));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Rectangle 118.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, 310, 350));

        jtbCoso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbCoso);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 520, 340));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Rectangle 3 (1).png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 540, 230));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/degradadoCircular.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, -30, 610, 410));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/degradadoCircular.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, -60, 650, 440));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Rectangle 3 (1).png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 540, 230));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/degradoFondo.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 290, 440, 390));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCRUD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField MarcaCRUD;
    public javax.swing.JTextField ModeloCRUD;
    public com.k33ptoo.components.KButton btnActualizar;
    public com.k33ptoo.components.KButton btnAgregar;
    public com.k33ptoo.components.KButton btnEliminar;
    public com.k33ptoo.components.KButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbCoso;
    public javax.swing.JTextField txtAnoCRUD;
    public javax.swing.JTextField txtApellidoCRUD;
    public javax.swing.JTextField txtEstadoProblemaCRUD;
    public javax.swing.JTextField txtNombreCRUD;
    public javax.swing.JTextField txtProblemaCRUD;
    public javax.swing.JTextField txtTelefonoCRUD1;
    // End of variables declaration//GEN-END:variables
}
